// packages/packs/target/frontend/src/nexti_pack_frontend/templates/react/src/App.tsx
import { useMemo, useState } from 'react'
import { createApi } from './api/client'
import { SCREENS, START } from './screens'

/** The shell: one screen at a time; a screen opens another with navigate(id). */
export default function App() {
  const api = useMemo(() => createApi(), [])
  const [current, setCurrent] = useState(START)
  const Screen = SCREENS[current]
  return Screen ? <Screen api={api} navigate={setCurrent} /> : null
}

// packages/packs/target/frontend/src/nexti_pack_frontend/templates/angular/src/app/app.component.ts
import { Component, signal } from '@angular/core'
import { NgComponentOutlet } from '@angular/common'
import { SCREENS, START } from '../screens'

/** The current screen of the shell; NAVIGATE changes it. */
export const current = signal(START)

@Component({
  selector: 'nx-app',
  standalone: true,
  imports: [NgComponentOutlet],
  template: `<ng-container *ngComponentOutlet="screen()" />`,
})
export class AppComponent {
  readonly screen = () => SCREENS[current()] ?? null
}
